name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run linter (flake8)
        run: flake8 server.py client.py

      - name: Run unit tests
        run: python -m unittest discover tests/
      
      - name: Create Release (Simulated Deployment)
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: Distributed Chat System Release ${{ github.run_number }}
          body: |
            This is an automated release created by CI/CD.

